[SYSTEM]
NEED_SIGN = false
NEED_ENCRYPT = false
USER_TOKEN = 'BRDVwHXVXQ3XMJSXo3vJ49IxKDZYxNa1'
TOKEN_NAME = 'BRDVwHXngLrGp8'
LOCAL_TOKEN = 'tGuxxHQ56uEngLrGp894JKbe3LkX2cVN'
OPEN_ID = '7B54GEa6bcigIEZP'

[SYSTEM.SIGNATURE]
CBCIV = 'poykrzGPHBph6wEs'
PUBLIC_KEY = 'Mu1kXIbe2RXk3W0eXTp5panFhuojrJke'
TRANSMIT_PARAM = 'encryptionData'
SIGNATURE_KEY = 'JvKCetawI23SN4AL7kayJasUjaLWv6Gie5tbj6xNM3dZ1esDlrKa1yejqDIIY5Hq'
MHMAC_SHA256_PUBLIC_KEY = "Svb9urigyQvxrfuj"

